appname = inscripcion_crud
httpport = ${INSCRIPCION_CRUD_HTTP_PORT}
runmode = ${INSCRIPCION_CRUD_RUN_MODE||prod}
autorender = false
copyrequestbody = true
EnableDocs = true
parameterStore = ${PARAMETER_STORE}
logPath= ${INSCRIPCION_CRUD_LOG}
PGuser=${INSCRIPCION_CRUD_PGUSER}
PGpass=${INSCRIPCION_CRUD_PGPASS}
PGhost=${INSCRIPCION_CRUD_PGHOST}
PGport=${INSCRIPCION_CRUD_PGPORT}
PGdb=${INSCRIPCION_CRUD_PGDB}
PGschema=${INSCRIPCION_CRUD_PGSCHEMA}